#Makefile for assignment 2
#Concepts of programming languages
#Ryan Behari, S3618765
#Universiteit Leiden

build:
	echo "Use make run {filenamewithexpression.txt} instead"

run:
	python assignment2.py $(EXPR)