#Makefile for assignment 3
#Concepts of programming languages
#Ryan Behari, S3618765
#Universiteit Leiden

build:
	echo "Use make run {filenamewithjudgement.txt} instead"

run:
	python assignment3.py $(JGMNT)